### ISSUE TITLE
6.2 cancel button in provider update page is bug

### ISSUE THREAD

**Issue by mameowwy** [2110336-2565-2/Sec1_Group5_Schoolar#34]
สมมติแก้ provider name จาก za เป็น zb ละกดอัพเดต -> database เปลี่ยนเป็น zb, ใน textfiled display zb แต่พอกด cancel ต่อเลย -> database เป็น zb เหมือนเดิม แต่ใน textfiled display za ซึ่งมันไม่ควรเป็นแบบนั้น มันควรจะ cancel แล้วกลับไป display zb เหมือนเดิม

**Comment by NonRoute** [comment]
This feature will be removed
